fixing mac analysis

diff --git a/analysis/dist/ccsh b/analysis/dist/ccsh
--- a/analysis/dist/ccsh
+++ b/analysis/dist/ccsh
@@ -1,7 +1,17 @@
 #!/usr/bin/env bash
 set -e
 
-CCSH_PATH=$(readlink -f "$0")
+case `uname` in
+ "Darwin") {
+     if !(which greadlink > /dev/null); then
+        echo 'ERROR: GNU utils required for Mac. You may use homebrew to install them: brew install coreutils gnu-sed'
+        exit 1
+     fi
+     CCSH_PATH=$(greadlink -f "$0")
+    } ;;
+ *)  CCSH_PATH=$(readlink -f "$0") ;;
+esac
+
 CC_INSTALL_DIR=$(dirname "${CCSH_PATH}")
 
 CC_VERSION="1.1.0"
